```{r include=FALSE}
library(nflfastR)
library(dplyr, warn.conflicts = FALSE)
library(tidyverse)
library(nflplotR)
source("buildFunctions.R")
current_season = 2022
knitr::opts_chunk$set(echo = TRUE)
nflreadr::.clear_cache()
options(dplyr.summarise.inform = FALSE)
current_season_schedule <- fast_scraper_schedules(current_season)

offense_pbp <- load_pbp(current_season) %>%
  filter(season_type == "REG") %>%
  filter(!is.na(posteam) & (rush == 1 | pass == 1))

scores <-
  offense_pbp[c(
    'game_id',
    'week',
    'home_team',
    'away_team',
    'season_type',
    'home_score',
    'away_score'
  )] %>%
  unique()

home_df <-
  scores[c('week', 'home_team', 'away_team', 'home_score', 'away_score')] %>%
  rename(team = home_team) %>%
  group_by(team) %>%
  mutate(
    oppositionTeam = away_team,
    PointsFor = mean(home_score),
    PointsAgainst = mean(away_score),
    win = if_else(home_score > away_score, 1, 0),
    pythWin = (PointsFor^13.91)/((PointsFor^13.91)+(PointsAgainst^13.91))
  ) %>%
  summarise(week,
            team,
            oppositionTeam,
            PointsFor,
            PointsAgainst,
            win,
            pythWin
            ) %>%
  unique()

away_df <-
  scores[c('week', 'away_team', 'home_team', 'home_score', 'away_score')] %>%
  rename(team = away_team) %>%
  group_by(team) %>%
  mutate(
    oppositionTeam = home_team,
    PointsFor = away_score,
    PointsAgainst = home_score,
    win = if_else(away_score > home_score, 1, 0),
    pythWin = (PointsFor^13.91)/((PointsFor^13.91)+(PointsAgainst^13.91))
  ) %>%
  summarize(week,
            team,
            oppositionTeam,
            PointsFor,
            PointsAgainst,
            win,
            pythWin
            ) %>%
  unique()

schedule_df <- rbind(x = away_df, y = home_df)
avg_points = mean(schedule_df$PointsFor)

team_df <- return_team_df(schedule_df)
```

# Team Data

The following are visuals and data that will help you with any Game Props or provide useful information to help you make more informed decisions when it comes to overall team-based results

## General Team Data

```{r warning = FALSE, message = FALSE}
ggplot(team_df, aes(x = pointsFor, y = pointsAgainst)) +
  geom_mean_lines(aes(h_var = pointsFor, v_var = pointsAgainst)) +
  geom_nfl_logos(aes(team_abbr = team), width = 0.07, alpha = 0.7) +
  labs(x = "PointsFor/Game",
       y = "PointsAgainst/Game",
       title = "2021-2022 NFL Average Points For vs Points Against") +
  theme_bw() +
  theme(plot.title = element_text(size = 12, hjust = 0.5, face = "bold")) +
  scale_y_reverse()
```
```{r, message = FALSE}
below500 <- team_df %>%
  filter(winPct < .501)

above500 <- team_df %>%
  filter(winPct > .500)

above500_df <- schedule_df %>%
  filter(oppositionTeam %in% above500$team) %>%
  group_by(team) %>%
  mutate(
    pointsFor = mean(PointsFor),
    pointsAgainst = mean(PointsAgainst),
    wins = sum(win),
    losses = sum(win == 0),
    winPct_above = wins / (wins + losses)
  ) %>%
  summarize(team,
            winPct_above) %>%
  unique()

below500_df <- schedule_df %>%
  filter(oppositionTeam %in% below500$team) %>%
  group_by(team) %>%
  mutate(
    pointsFor = mean(PointsFor),
    pointsAgainst = mean(PointsAgainst),
    wins = sum(win),
    losses = sum(win == 0),
    winPct_below = wins / (wins + losses)
  ) %>%
  summarize(team,
            winPct_below) %>%
  unique()

winPct500 <- merge(above500_df, below500_df, by = "team")

ggplot(winPct500, aes(x = winPct_below, y = winPct_above)) +
  geom_mean_lines(aes(h_var = winPct_below, v_var = winPct_above)) +
  geom_nfl_logos(aes(team_abbr = team), width = 0.07, alpha = 0.7) +
  labs(x = "Win% vs Teams Below .500",
       y = "Win% vs Teams Above .500",
       title = "2022-2023 NFL Win% vs teams above .500 and below") +
  theme_bw() +
  theme(plot.title = element_text(size = 12, hjust = 0.5, face = "bold"))
```

```{r, message = FALSE}
ggplot(team_df, aes(x = wins, y = pythWin)) +
  geom_mean_lines(aes(h_var = wins, v_var = pythWin)) +
  geom_nfl_logos(aes(team_abbr = team), width = 0.07, alpha = 0.7) +
  labs(x = "# Of Wins",
       y = "# Of Pythagorean Expected Wins",
       title = "2022-2023 Wins vs Pythagorean Expected Wins") +
  theme_bw() +
  theme(plot.title = element_text(size = 12, hjust = 0.5, face = "bold"))

```

```{r, message = FALSE}
ggplot(team_df, aes(x = pointsFor, y = netPF)) +
  geom_mean_lines(aes(h_var = pointsFor, v_var = netPF)) +
  geom_nfl_logos(aes(team_abbr = team), width = 0.07, alpha = 0.7) +
  labs(x = "Actual Points For",
       y = "Weighted Points For",
       title = "2022-2023 NFL Points For vs Weighted Points For Based On Opponent") +
  theme_bw() +
  theme(plot.title = element_text(size = 12, hjust = 0.5, face = "bold"))

```

``` {r, message = FALSE}
ggplot(team_df, aes(x = pointsAgainst, y = netPA)) +
  geom_mean_lines(aes(h_var = pointsAgainst, v_var = netPA)) +
  geom_nfl_logos(aes(team_abbr = team), width = 0.07, alpha = 0.7) +
  labs(x = "Actual Points Against",
       y = "Weighted Points Against",
       title = "2022-2023 NFL Points Against vs Weighted Points Against Based On Opponent") +
  theme_bw() +
  theme(plot.title = element_text(size = 12, hjust = 0.5, face = "bold"))+
  scale_y_reverse()+
  scale_x_reverse()
```