---
title: "qbData"
output: html_document
date: "2022-12-01"
---

```{r setup, include=FALSE}
library(nflfastR)
library(dplyr, warn.conflicts = FALSE)
library(tidyverse)
library(nflplotR)
library(ggrepel)
library(knitr)
library(forcats)
library(ggpubr)
knitr::opts_chunk$set(echo = TRUE)
nflreadr::.clear_cache()
```

## File in which we analyze NFL QB's and their effectiveness.

```{r cars}
pbp <- load_pbp(2022) %>%
  filter(season_type == "REG") %>%
  filter(!is.na(posteam) & (pass == 1) & (!is.na(passer)))
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE, warning = FALSE, message = FALSE}
epaPerPass <- pbp %>%
  group_by(passer) %>%
  mutate(totalAttempts = n(),
         avg_epa = mean(qb_epa),
         shortPass = mean(air_yards < 10, na.rm = T),
         mediumPass = mean((10 <= air_yards & air_yards <= 25), na.rm = T),
         longPass = mean(air_yards > 25, na.rm = T)
         ) %>%
  summarize(passer,
            totalAttempts,
            avg_epa,
            shortPass,
            mediumPass,
            longPass
            ) %>%
  filter(totalAttempts > 110) %>%
  unique()

pbp <- pbp %>%
  filter(passer %in% epaPerPass$passer)

ggplot(epaPerPass, aes(x = totalAttempts, y = avg_epa, label = passer)) +
  geom_point() +
  geom_label_repel(
    min.segment.length = 0,
    max.overlaps = Inf,
    label.size = 0,
    label.padding = 0,
    label.r = 0,
    size = 4,
    family = "Monstercat"
  ) +
  geom_smooth(
    method = lm,
    se = FALSE,
    col = 'red',
    linetype = 'dashed'
  )
```
```{r fig.width = 25}
data1 <- epaPerPass
long_sorted <- data1 # Replicate original data
long_sorted$passer <- factor(long_sorted$passer, # Factor levels in decreasing order
                  levels = long_sorted$passer[order(long_sorted$longPass, decreasing = TRUE)])

medium_sorted <- data1 
medium_sorted$passer <- factor(medium_sorted$passer,                                  
                 levels = medium_sorted$passer[order(medium_sorted$mediumPass, decreasing = TRUE)])

short_sorted <- data1 
short_sorted$passer <- factor(short_sorted$passer,                                  
                 levels = short_sorted$passer[order(short_sorted$shortPass, decreasing = TRUE)])

longPct_graph <- long_sorted %>%
  ggplot(aes(x = passer, y = longPass)) +
  ggtitle("Percentage of Pass Attempts >25 Yards") +
  geom_bar(stat = "identity", width = 0.7, fill = "#bc4b51") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

mediumPct_graph <- medium_sorted %>%
  ggplot(aes(x = passer, y = mediumPass)) +
  ggtitle("Percentage of Pass Attempts within 10-25 Yards") +
  geom_bar(stat = "identity", width = 0.7, fill = "#f4a259") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

shortPct_graph <-short_sorted %>%
  ggplot(aes(x = passer, y = shortPass)) +
  ggtitle("Percentage of Pass Attempts <10 Yards") +
  geom_bar(stat = "identity", width = 0.7, fill = "#8cb369") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

ggarrange(longPct_graph, mediumPct_graph, shortPct_graph,
          ncol = 1, nrow = 3)

```
```{r fig.width = 45}

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
